server.port=8088
# en PostMan es pabellones
spring.datasource.url=jdbc:mysql://localhost:3306/mspabellon
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true